name: Publish mhtml-to-html-py to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.1.0, v1.2.3, etc.
  workflow_dispatch:  # Allow manual triggering

permissions:
  id-token: write  # Required for PyPI trusted publishing
  contents: write  # Required for creating releases
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi  # This should match what you configure in PyPI
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for ${{ github.ref_name }}
          
          ## What's Changed
          - See commit history for detailed changes
          
          ## Installation
          ```bash
          pip install mhtml-to-html-py
          ```
          
          ## Credits
          This Python package wraps the excellent [gonejack/mhtml-to-html](https://github.com/gonejack/mhtml-to-html) Go tool.
        draft: false
        prerelease: false
        files: |
          dist/*.whl
          dist/*.tar.gz
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/ 